learning_site/courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/t(?P<step_pk>\d+)/$', views.text_step,
        name='text_step'),
    url(r'(?P<course_pk>\d+)/q(?P<step_pk>\d+)/$', views.quiz_step,
        name='quiz_step'),
    url(r'(?P<course_pk>\d+)/create_quiz/$', views.quiz_create,
        name='create_quiz'),
    url(r'(?P<course_pk>\d+)/edit_quiz/(?P<quiz_pk>\d+)/$', views.quiz_edit,
        name='edit_quiz'),
    url(r'(?P<quiz_pk>\d+)/create_question/(?P<question_type>mc|tf)/$',
        views.create_question, name='create_question'),
    url(r'(?P<quiz_pk>\d+)/edit_question/(?P<question_pk>\d+)/$',
        views.edit_question, name='edit_question'),
    url(r'(?P<question_pk>\d+)/add_answer/$',
        views.answer_form, name='add_answer'),
    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
]

learning_site/learning_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^suggestions/', views.suggestion_view, name='suggestion'),
    url(r'^$', views.hello_world, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

learning_site/courses/models.py
from django.core.urlresolvers import reverse
from django.db import models

import math

STATUS_CHOICES = (
  ('i', 'In Progress'),
  ('r', 'In Review'),
  ('p', 'In Published'),
)

class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_live = models.BooleanField(default=False)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='i')
    
    def __str__(self):
        return self.title
    
    def time_to_complete(self):
        from courses.templatetags.course_extras import time_estimate
        return '{} min.'.format(time_estimate(len(self.description.split())))

class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)

    class Meta:
        abstract = True
        ordering = ['order',]

    def __str__(self):
        return self.title


class Text(Step):
    content = models.TextField(blank=True, default='')

    def get_absolute_url(self):
        return reverse('courses:text_step', kwargs={
            'course_pk': self.course.pk,
            'step_pk': self.pk
        })


class Quiz(Step):
    total_questions = models.IntegerField()

    class Meta:
        verbose_name_plural = "quizzes"

    def get_absolute_url(self):
        return reverse('courses:quiz_step', kwargs={
            'course_pk': self.course.pk,
            'step_pk': self.pk
        })
    
    def number_correct_needed(self):
        return '{}/{}'.format(math.ceil(self.total_questions * 0.7), self.total_questions)



class Question(models.Model):
    quiz = models.ForeignKey(Quiz)
    order = models.IntegerField(default=0)
    prompt = models.TextField()

    class Meta:
        ordering = ['order',]

    def get_absolute_url(self):
        return self.quiz.get_absolute_url()

    def __str__(self):
        return self.prompt


class MultipleChoiceQuestion(Question):
    shuffle_answers = models.BooleanField(default=False)


class TrueFalseQuestion(Question):
    pass


class Answer(models.Model):
    question = models.ForeignKey(Question)
    order = models.IntegerField(default=0)
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.text

learning_site/courses/forms.py
from django import forms

from . import models


class QuizForm(forms.ModelForm):
    class Meta:
        model = models.Quiz
        fields = [
            'title',
            'description',
            'order',
            'total_questions'
        ]


class QuestionForm(forms.ModelForm):
    class Media:
        css = {'all': ('courses/css/order.css',)}
        js = (
            'courses/js/vendor/jquery.fn.sortable.min.js',
            'courses/js/order.js'
        )


class TrueFalseQuestionForm(QuestionForm):
    class Meta:
        model = models.TrueFalseQuestion
        fields = [
            'order',
            'prompt',
        ]


class MultipleChoiceQuestionForm(QuestionForm):
    class Meta:
        model = models.MultipleChoiceQuestion
        fields = [
            'order',
            'prompt',
            'shuffle_answers'
        ]


class AnswerForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = [
            'order',
            'text',
            'correct'
        ]


AnswerFormSet = forms.modelformset_factory(
    models.Answer,
    form=AnswerForm,
)

AnswerInlineFormSet = forms.inlineformset_factory(
    models.Question,
    models.Answer,
    extra=0,
    fields=('order', 'text', 'correct'),
    formset=AnswerFormSet,
    min_num=1,
    widgets={'order': forms.TextInput(attrs={'readonly': True})}
)

learning_site/courses/views.py
from itertools import chain

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from . import forms
from . import models


def course_list(request):
    courses = models.Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})


def course_detail(request, pk):
    course = get_object_or_404(models.Course, pk=pk)
    steps = sorted(chain(course.text_set.all(), course.quiz_set.all()),
                   key=lambda s: s.order)
    return render(request, 'courses/course_detail.html', {
        'course': course,
        'steps': steps
    })


def text_step(request, course_pk, step_pk):
    step = get_object_or_404(models.Text, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/text_step.html', {'step': step})


def quiz_step(request, course_pk, step_pk):
    step = get_object_or_404(models.Quiz, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/quiz_step.html', {'step': step})


@login_required
def quiz_create(request, course_pk):
    course = get_object_or_404(models.Course, pk=course_pk)
    form = forms.QuizForm()
    if request.method == 'POST':
        form = forms.QuizForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.course = course
            quiz.save()
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/quiz_form.html', {
        'course': course,
        'form': form
    })


@login_required
def quiz_edit(request, course_pk, quiz_pk):
    quiz = get_object_or_404(models.Quiz, pk=quiz_pk, course_id=course_pk)
    form = forms.QuizForm(instance=quiz)
    if request.method == 'POST':
        form = forms.QuizForm(instance=quiz, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated {}".format(quiz.title))
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/quiz_form.html', {
        'course': quiz.course,
        'form': form
    })


@login_required
def create_question(request, quiz_pk, question_type):
    quiz = get_object_or_404(models.Quiz, pk=quiz_pk)
    if question_type == 'tf':
        form_class = forms.TrueFalseQuestionForm
    else:
        form_class = forms.MultipleChoiceQuestionForm

    form = form_class()
    answer_forms = forms.AnswerInlineFormSet(
        queryset=models.Answer.objects.none()
    )

    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            messages.success(request, "Added question")
            return HttpResponseRedirect(quiz.get_absolute_url())

    return render(request, 'courses/question_form.html', {
        'quiz': quiz,
        'form': form,
        'formset': answer_forms
    })


@login_required
def edit_question(request, quiz_pk, question_pk):
    question = get_object_or_404(models.Question,
                                 pk=question_pk, quiz_id=quiz_pk)
    if hasattr(question, 'truefalsequestion'):
        form_class = forms.TrueFalseQuestionForm
    else:
        form_class = forms.MultipleChoiceQuestionForm

    form = form_class(instance=question)
    answer_forms = forms.AnswerInlineFormSet(
        queryset=form.instance.answer_set.all()
    )

    if request.method == 'POST':
        form = form_class(request.POST, instance=question)
        answer_forms = forms.AnswerInlineFormSet(request.POST)
        if form.is_valid() and answer_forms.is_valid():
            form.save()
            answer_forms.save()
            messages.success(request, "Updated question")
            return HttpResponseRedirect(form.instance.get_absolute_url())

    return render(request, 'courses/question_form.html', {
        'quiz': question.quiz,
        'form': form,
        'formset': answer_forms
    })


@login_required
def answer_form(request, question_pk):
    question = get_object_or_404(models.Question, pk=question_pk)
    form = forms.AnswerForm()

    if request.method == 'POST':
        form = forms.AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.save()
            messages.success(request, "Added answer")
            return HttpResponseRedirect(question.quiz.get_absolute_url())
    return render(request, 'courses/answer_form.html', {'form': form})

learning_site/courses/templates/courses/answer_form.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button" value="Save">
        </form>
    </div>
{% endblock %}

learning_site/courses/templates/courses/course_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
        <article>
            <h1 class="">{{ course.title }}</h1>

            <div class="callout secondary">
                {{ course.description|markdown_to_html }}
            </div>

            <dl>
                {% for step in steps %}
                    <dt>
                        <a href="{{ step.get_absolute_url }}">{{ step.title }}</a>
                    </dt>
                    <dd>{{ step.description|markdown_to_html }}</dd>
                {% endfor %}
            </dl>
        </article>
        {% if user.is_superuser %}
            <hr>
            <a href="{% url 'courses:create_quiz' course_pk=course.pk %}" class="small button">Add Quiz</a>
        {% endif %}
    </div>
{% endblock %}

learning_site/courses/templates/courses/course_list.html
{% extends "courses/layout.html" %}

{% block title %}All{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
    </div>
    <div class="row">
        {%  for course in courses %}
            <div class="small-6 columns">
                <div class="callout">
                    <h5><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></h5>
                    <div class="card-copy">
                        {{ course.description }}
                    </div>
                </div>
            </div>

            {% if forloop.counter|divisibleby:"2" %}
                </div>
                <div class="row">
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

learning_site/courses/templates/courses/course_nav.html
{% for course in courses %} 
    <li><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></li>
{% endfor %}

learning_site/courses/templates/courses/layout.html
{% extends "layout.html" %}

{% block title %}Courses | {{ block.super }}{% endblock %}

{% block content %}
    {{ block.super }}
    <ul class="breadcrumbs">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'courses:list' %}">Courses</a></li>
        {% block breadcrumbs %}{% endblock %}
    </ul>
{% endblock %}

learning_site/courses/templates/courses/question_form.html
{% extends "courses/layout.html" %}

{% block title %}
    {{ block.super }}
    {% if form.instance.pk %}
        {{ form.instance.prompt }}
    {% else %}
        New question
    {% endif %}
{% endblock %}

{% block css %}
    {{ form.media.css }}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:quiz_step' course_pk=quiz.course_id step_pk=quiz.pk %}">{{ quiz.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
    </div>
    <div class="row columns">
        <form method="POST" class="small-12">
            {% csrf_token %}
            {{ form.as_p }}
            {{ formset.management_form }}
            <table role="grid" class="stack hover" style="width: 100%">
                <thead>
                    <tr>
                        <th scope="col" class="text-center" style="width:10%">Order</th>
                        <th scope="col">Text</th>
                        <th scope="col" class="text-center" style="width:10%">Correct?</th>
                        <th scope="col" class="text-center" style="width:10%">Delete?</th>
                    </tr>
                </thead>
                <tbody class="order">
                    {% for form in formset %}
                        <tr class="answer-form {% if form.instance.pk %}item{% else %}new{% endif %}">
                            <td>{{ form.id }}{{ form.order }}</td>
                            <td>{{ form.text }}</td>
                            <td class="text-center">{{ form.correct }}</td>
                            {% if form.instance.pk %}
                                <td class="text-center">{{ form.DELETE }}</td>
                            {% else %}
                                <td class="text-center"></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <input type="submit" class="button" value="Save">
        </form>
    </div>
{% endblock %}

{% block javascript %}
    {% load static from staticfiles %}
    {{ form.media.js }}
    <script src="{% static 'js/vendor/jquery.formset.js' %}"></script>
    <script>
        $('.answer-form').formset({
            addText: 'add answer',
            deleteText: 'remove'
        });
    </script>
{% endblock %}

learning_site/courses/templates/courses/quiz_form.html
{% extends "courses/layout.html" %}

{% block title %}
    {{ block.super }}
    {% if form.instance.pk %}
        {{ form.instance.title }}
    {% else %}
        New Quiz
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=course.id %}">{{ course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
        <h1>{{ form.instance.title|default:"Make a new quiz" }}</h1>
        <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button" value="Save">
        </form>
    </div>
{% endblock %}

learning_site/courses/templates/courses/quiz_step.html
{% extends "courses/layout.html" %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            <ul class="no-bullet">
            {% for question in step.question_set.all %}
                <li>
                    <h3 class="subheader">{{ question.prompt }}</h3>
                    {% for answer in question.answer_set.all %}
                        <div class="callout {% if answer.correct and user.is_superuser%}success{% endif %}">{{ answer.text }}</div>
                    {% endfor %}
                    {% if user.is_superuser %}
                        <a href="{% url 'courses:edit_question' question_pk=question.pk quiz_pk=step.pk %}" class="tiny button">Edit Question</a>
                    {% endif %}
                </li>
            {% endfor %}
            </ul>
        {% if user.is_superuser %}
            <hr>
            <div class="button-group">
                <a href="{% url 'courses:edit_quiz' course_pk=step.course_id quiz_pk=step.pk %}" class="small button">Edit Quiz</a>
                <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type='mc' %}" class="small button">Add Multiple Choice</a>
                <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type='tf' %}" class="small button">Add True/False</a>
            </div>
        {% endif %}
        </article>
    </div>
{% endblock %}

learning_site/courses/templates/courses/text_step.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            {{ step.content|markdown_to_html }}
        </article>
    </div>
{% endblock %}